name: hola-mundo #Nombre del workflow
on: [push] #evento que lo activará
jobs: #Definición de los jobs
    hola-mundo: #Nombre del job
        runs-on: ubuntu-latest #Maquina en la que correrá
        steps: #Lista de steps del job hola-mundo
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
                with:
                node-version: 18
            - name: Run index
                run: node index.js
